# Generated by Django 4.2.7 on 2024-01-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rian', '0002_alter_kategori_options_alter_kontak_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Chat ID',
            },
        ),
    ]
